export const GET_COUSER = 'GET_COUSER'
export const GET_COUSER_SUCCESS = 'GET_COUSER_SUCCESS'

export const COUSER_REGISTER = 'COUSER_REGISTER'
export const COUSER_REGISTER_SUCCESS = 'COUSER_REGISTER_SUCCESS'

export const COUSER_UNREGISTER = 'COUSER_UNREGISTER'
export const COUSER_UNREGISTER_SUCCESS = 'COUSER_UNREGISTER_SUCCESS'
